config/routes.rb
Rails.application.routes.draw do
  resources :users

    root 'pages#home'
	
		
	get 'welcome' => 'pages#home'
	get '/pages' => 'pages#home'
	
	get '/messages' => 'messages#index'
	get '/messages/new' => 'messages#new'
	post 'messages' => 'messages#create'
	
	get '/tags' => 'tags#index'
	get '/tags/:id' => 'tags#show', as: :tag
	get '/destinations/:id' => 'destinations#show', as: :destination
	get '/destinations/:id/edit' => 'destinations#edit', as: :edit_destination
	patch '/destinations/:id' => 'destinations#update'
	
	get '/movies' => 'movies#index'
	get '/movies/:id' => 'movies#show', as: :movie
	
	get '/actors' => 'actors#index'
	get '/actors/:id' => 'actors#show', as: :actor
	
	get '/signup'  => 'users#new'
	get '/users/:id' => 'users#show'
	get '/users/:id/edit' => 'users#edit'
	post "signup" => 'users#create'
	resources :users
	
	get '/login' => 'sessions#new'
	post 'login' => 'sessions#create'
  
	delete 'logout' => 'sessions#destroy'
  
  

end

app/models/actor.rb
class Actor < ActiveRecord::Base
	has_many :parts
	has_many :movies, through: :parts
end

app/models/destination.rb
class Destination < ActiveRecord::Base
	belongs_to :tag
end

app/models/message.rb
class Message < ActiveRecord::Base
end

app/models/movie.rb
class Movie < ActiveRecord::Base
	has_many :parts
	has_many :actors, through: :parts
end

app/models/part.rb
class Part < ActiveRecord::Base
	belongs_to :movie
	belongs_to :actor
end

app/models/tag.rb
class Tag < ActiveRecord::Base
	has_many :destinations
end

app/models/user.rb
class User < ActiveRecord::Base
end

app/controllers/actors_controller.rb
class ActorsController < ApplicationController
	def index
		@actors = Actor.all
	end
	
	def show
    @actor = Actor.find(params[:id])
    @movies = @actor.movies
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
	def index
		@messages = Message.all
	end
	
	def new
		@message = Message.new
	end
	
	def create 
  	@message = Message.new(message_params) 
  	if @message.save 
    	redirect_to '/messages' 
  	else 
    	render 'new' 
  	end 
	end
	
	private
	
  	def message_params 
    	params.require(:message).permit(:content) 
  	end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
	def index
		@movies = Movie.all
	end

	def show
		@movie = Movie.find(params[:id])
		@actors = @movie.actors
	end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	def home
	end
	def house
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
	def index
		@tags = Tag.all
	end
	def show
		@tag = Tag.find(params[:id])
		@destinations = @tag.destinations
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
		@user = User.find(params[:id])
  end

  # GET /users/new
  def new
		@user = User.new
  end

  # GET /users/1/edit
  def edit
		@user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:first_name, :last_name, :email, :password_digest)
    end
end

app/helpers/actors_helper.rb
module ActorsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/destinations_helper.rb
module DestinationsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/actors/index.html.erb
<div class="main actor-index">
	<div class="container">
		<div class="row">
			<% @actors.each do |actor| %>
			<div class="actor col-xs-2">
				<%= image_tag actor.image %>
				<h3><%= actor.first_name + " " + actor.last_name %></h3>
				<%= link_to "Learn more", actor_path(actor) %>
			</div>
			<% end %>
		</div>
	</div>
</div>

app/views/actors/show.html.erb
<div class="main actor-show">
  <div class="container">
    
    <!-- Display an actor's info here -->
    <div class="actor">
      <%= image_tag @actor.image %>
      <div class="info">
        <h3 class="actor-name"><%= @actor.first_name + " " + @actor.last_name  %></h3>
        <p class="actor-bio"><%= @actor.bio %></p>
      </div>
    </div>

    <h2>Movies</h2>
    <% @movies.each do |movie| %>
    <div class="movie">
      <%= image_tag movie.image %>
      <h3 class="movie-title"><%= movie.title %></h3>
      <p class="movie-release-year"><%= movie.release_year %></p>
      <p class="movie-plot"><%= movie.plot %></p>
	  <%= link_to "Learn more", movie_path(movie) %>
    </div>
    <% end %>

  </div>
</div>

app/views/messages/index.html.erb
<div class="header">
  <div class="container">
    <img src="http://s3.amazonaws.com/codecademy-content/courses/learn-rails/img/logo-1m.svg">
    <h1>Messenger</h1>
  </div>
</div>

<div class="messages">
  <div class="container">
  	<% @messages.each do |message| %> 
			<div class="message"> 
  			<p class="content"><%= message.content %></p> 
  			<p class="time"><%= message.created_at %></p> 
			</div> 
		<% end %>
		<%= link_to 'New Message', "messages/new" %>
  </div>
</div>

app/views/messages/new.html.erb
<div class="header">
  <div class="container">
    <img src="http://s3.amazonaws.com/codecademy-content/courses/learn-rails/img/logo-1m.svg">
    <h1>Messenger</h1>
  </div>
</div>

<div class="create">
  <div class="container">
   	<%= form_for(@message) do |f| %>  
  		<div class="field"> 
    		<%= f.label :message %><br> 
    		<%= f.text_area :content %> 
  		</div> 
  		<div class="actions"> 
    		<%= f.submit "Create" %> 
  		</div> 
		<% end %>
  </div>
</div>

app/views/tags/index.html.erb
<div class="header">
  <div class="container">
    <img src="http://s3.amazonaws.com/codecademy-content/courses/learn-rails/img/logo-1tm.svg" width="80">
    <h1>BokenjiKan</h1>
  </div>
</div>

<div class="tags">
  <div class="container">
    <div class="cards row">
    	<% @tags.each do |t| %>
      <div class="card col-xs-4">
        <%= image_tag t.image %>
        <h2><%= t.title %></h2>
        <%= link_to "Learn more", tag_path(t) %>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/tags/show.html.erb
<div class="header">
  <div class="container">
    <img src="http://s3.amazonaws.com/codecademy-content/courses/learn-rails/img/logo-1tm.svg" width="80">
    <h1>BokenjiKan</h1>
  </div>
</div>

<div class="tag">
  <div class="container">
    <h2><%= @tag.title %></h2>

    <div class="cards row">
      <% @destinations.each do |d| %>
      <div class="card col-xs-4">
        <%= image_tag d.image %>
        <h2><%= d.name %></h2>
        <p><%= d.description %></p>
        <%= link_to "See more", destination_path(d) %>
      </div>
      <% end %>
    </div>

  </div>
</div>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
   <div class="field">
    <%= f.label :password %><br>
    <%= f.text_field :password_digest %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.first_name %></td>
		<td><%= user.last_name %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<div class="login">
	<div class="container">
		<div class="form">
		
		<h1>Sign up</h1>

		<%= form_for(@user) do |f| %>
			<%= f.text_field :first_name, :placeholder => "First name" %>
			<%= f.text_field :last_name, :placeholder => "Last name" %>
			<%= f.email_field :email, :placeholder => "Email" %>
			<%= f.password_field :password, :placeholder => "Password" %>
			<%= f.submit "Create an account", class: "btn-submit" %>
		<% end %>
		</div>
	</div>

</div>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>FirstName:</strong>
  <%= @user.first_name %>
</p>
<p>
  <strong>LastName:</strong>
  <%= @user.last_name %>
</p>
<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>